apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: planka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-data
  namespace: planka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
